identifier: name: itsybitsy_nrf52840
name: Adafruit ItsyBitsy nRF52840 express
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
supported:
  - adc
  - usb_device
  - usb_cdc
  - ble
  - ieee802154
  - pwm
  - watchdog
  - counter
